Use sysctls available in macOS 12 / iOS 15 for hardware feature support.
pytorch/cpuinfo pull request #100
Opened 2022-07-12 16:59 UTC by kulinseth

2022-07-14 17:08 UTC, kulinseth commented
@malfet ping for review.

2022-07-18 16:50 UTC, Maratyszcza requested changes
Use lower-case for variable names, i.e. `has_feat_lse` instead of `has_FEAT_LSE`

2022-07-18 16:50 UTC, Maratyszcza commented on src/arm/mach/init.c
> +	 * iOS 15 and macOS 12 added sysctls for Arm features.  Use them where
Nit: Arm->ARM

2022-07-25 18:33 UTC, Maratyszcza requested changes
Please use lowercase variable names (i.e. `has_feat_lse` rather than `has_FEAT_LSE`). Other than that, the PR LGTM.

2022-07-25 18:53 UTC, merged

2022-07-25 18:53 UTC, Maratyszcza commented
Thank you!