Add support for Arm FHM
pytorch/cpuinfo pull request #102
Opened 2022-07-12 17:00 UTC by kulinseth

2022-07-14 17:08 UTC, kulinseth commented
@malfet ping for review.

2022-07-15 16:26 UTC, malfet approved these changes

2022-07-15 16:40 UTC, malfet approved these changes

2022-07-16 00:36 UTC, kulinseth commented
@pytorchbot rebase

2022-07-18 16:45 UTC, Maratyszcza requested changes

2022-07-18 16:45 UTC, Maratyszcza commented on src/arm/mach/init.c
> +	const uint32_t has_FEAT_FHM = get_sys_info_by_name("hw.optional.arm.FEAT_FHM");
Use lower-case characters in identifiers, i.e. `has_feat_fhm`

2022-07-18 16:45 UTC, Maratyszcza commented on src/arm/mach/init.c
> +		const uint32_t has_FEAT_FHM_legacy = get_sys_info_by_name("hw.optional.armv8_2_fhm");
Ditto

2022-07-18 16:45 UTC, Maratyszcza commented on include/cpuinfo.h
> +
Move right after `cpuinfo_has_arm_fp16_arith` as these two are related.

2022-07-18 16:45 UTC, Maratyszcza commented on tools/isa-info.c
> +		printf("\tFMLAL/FMLSL: %s\n", cpuinfo_has_arm_fhm() ? "yes" : "no");
Don't report it under "Floating-Point" section because these are SIMD-only instructions

2022-07-18 16:45 UTC, Maratyszcza commented on tools/isa-info.c
> +		printf("\tARM v8.2 FHM: %s\n", cpuinfo_has_arm_fhm() ? "yes" : "no");
Move one line up to group with "FP16 arithmetics" which is closely related

2022-07-18 17:49 UTC, kulinseth commented
@Maratyszcza addressed your comments. Thanks.

2022-07-18 17:53 UTC, kulinseth commented
@malfet , 
```
/home/runner/work/cpuinfo/cpuinfo/src/arm/linux/cpuinfo.c:291:29: error: use of undeclared identifier 'CPUINFO_ARM_LINUX_FEATURE_ASIMDFHM'
[86](https://github.com/pytorch/cpuinfo/runs/7395025124?check_suite_focus=true#step:6:87)
                                        processor->features |= CPUINFO_ARM_LINUX_FEATURE_ASIMDFHM;
[87](https://github.com/pytorch/cpuinfo/runs/7395025124?check_suite_focus=true#step:6:88)
                                                               ^
[88](https://github.com/pytorch/cpuinfo/runs/7395025124?check_suite_focus=true#step:6:89)
1 error generated.
[89](https://github.com/pytorch/cpuinfo/runs/7395025124?check_suite_focus=true#step:6:90)
[7/239] Building C object CMakeFiles/cpuinfo.dir/src/arm/linux/init.c.o
[90](https://github.com/pytorch/cpuinfo/runs/7395025124?check_suite_focus=true#step:6:91)
ninja: build stopped: subcommand failed.
[91](https://github.com/pytorch/cpuinfo/runs/7395025124?check_suite_focus=true#step:6:92)
Error: Process completed with exit code 1.
```
This looks like genuine failure. Do we need to make this Mac arm specific ?

2022-07-18 18:34 UTC, Maratyszcza requested changes

2022-07-18 18:34 UTC, Maratyszcza commented on src/arm/linux/cpuinfo.c
> +					processor->features |= CPUINFO_ARM_LINUX_FEATURE_ASIMDFHM;
Wrap in `#if CPUINFO_ARCH_ARM64`

2022-07-26 17:51 UTC, kulinseth commented on src/arm/linux/aarch64-isa.c
> +	if (features2 & CPUINFO_ARM_LINUX_FEATURE2_SVEBF16) {
I see, I locally build and I am not seeing build failure when I run the `sh scripts/local-build.sh` and then I test with `build/bin/init-test` binary.

2022-07-26 17:52 UTC, kulinseth commented on src/arm/linux/aarch64-isa.c
> +	if (features2 & CPUINFO_ARM_LINUX_FEATURE2_SVEBF16) {
Regardless I removed the line.

2022-07-26 17:56 UTC, kulinseth commented
> Fails on AArch32 because identifier is only defined on AArch64

Thanks, removed that line.

2022-07-26 21:44 UTC, Maratyszcza requested changes
Thanks! Last formatting changes, and it is good to go

2022-07-26 21:44 UTC, Maratyszcza commented on src/arm/linux/cpuinfo.c
> +					processor->features |= CPUINFO_ARM_LINUX_FEATURE_ASIMDFHM;
Indent the line as if it was within a normal `if` block

2022-07-26 21:44 UTC, Maratyszcza commented on src/arm/linux/aarch64-isa.c
> +
Remove the extra newline

2022-07-27 01:11 UTC, Maratyszcza approved these changes

2022-07-27 01:25 UTC, merged