Enable CXX only when needed for tests
pytorch/cpuinfo pull request #133
Opened 2023-01-29 23:57 UTC by jameshilliard

We shouldn't require CXX support in the project as it's only needed for tests.

2023-02-14 21:07 UTC, Maratyszcza requested changes
Benchmarks also require C++

2023-02-14 21:51 UTC, jameshilliard commented
> Benchmarks also require C++

Enabled C++ for benchmarks as well.

2023-03-09 04:37 UTC, Maratyszcza approved these changes

2023-03-09 04:45 UTC, Maratyszcza commented
CI build fails, PTAL

2023-03-09 09:58 UTC, jameshilliard commented
> CI build fails, PTAL

Yeah, needed to move the `ENABLE_LANGUAGE` block down a bit after `CPUINFO_SUPPORTED_PLATFORM` is defined/set.

2023-03-09 15:23 UTC, Maratyszcza commented on CMakeLists.txt
> +  IF(CPUINFO_BUILD_UNIT_TESTS OR CPUINFO_BUILD_BENCHMARKS)
Check `CPUINFO_BUILD_MOCK_TESTS` as well

2023-03-09 23:55 UTC, jameshilliard commented on CMakeLists.txt
> +  IF(CPUINFO_BUILD_UNIT_TESTS OR CPUINFO_BUILD_BENCHMARKS)
added

2023-08-16 20:14 UTC, merged